# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuntCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HuntUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clue', models.CharField(max_length=120)),
                ('question', models.CharField(max_length=120)),
                ('answer', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_landmark', models.IntegerField(default=0)),
                ('penalty_count', models.IntegerField(default=0)),
                ('clue_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TimeDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delta', models.DurationField(default=datetime.timedelta(0))),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_log', to='eScavenge.Team')),
            ],
        ),
        migrations.AddField(
            model_name='huntcommand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScavenge.HuntUser'),
        ),
    ]
