# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:55
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('penalty_value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('penalty_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('timer', models.DurationField(blank=True, null=True)),
                ('landmark_points', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('clue', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='eScavenge.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_landmark', models.IntegerField(default=0)),
                ('penalty_count', models.IntegerField(default=0)),
                ('clue_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='eScavenge.Game')),
            ],
        ),
        migrations.CreateModel(
            name='TimeDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delta', models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_log', to='eScavenge.Team')),
            ],
        ),
    ]
