# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:31
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScavenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delta', models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quit', models.BooleanField()),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='eScavenge.Landmark')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='eScavenge.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='timedelta',
            name='team',
        ),
        migrations.DeleteModel(
            name='TimeDelta',
        ),
    ]
