# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScavenge', '0002_team_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('clue', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
